// Default configuration matching framework defaults
export const defaultConfig = {
  // Colors
  colors: {
    black: '#1a1a1a',
    white: '#ffffff',
    warmGray: '#f5f2ed',
    darkGray: '#333333',
    mediumGray: '#666666',
    lightGray: '#e8e5e0',
    red: '#c1272d',
    brown: '#4a3728',
    green: '#2d5a27',
    blue: '#274a5a',
  },

  // Typography
  fontFamily: 'Inter, sans-serif',
  fontFamilyVariable: 'InterVariable, sans-serif',
  baseFontSize: 100,       // %
  baseFontSizeDesktop: 112.5, // %
  baseLeading: 1.625,
  baseLeadingDesktop: 1.7,

  // Border Radius
  borderRadius: 0,  // px or rem

  // Components to include
  components: {
    reset: true,
    container: true,
    grid: true,
    formats: true,
    broadside: true,
    header: true,
    navbar: true,
    footer: true,
    hero: true,
    section: true,
    typography: true,
    prose: true,
    buttons: true,
    dropdown: true,
    tabs: true,
    accordion: true,
    table: true,
    list: true,
    card: true,
    sidebar: true,
    forms: true,
    modal: true,
    pagination: true,
    scrollspy: true,
    modules: true,
    utilities: true,
  },

  // JS components to include
  js: {
    dropdown: true,
    tabs: true,
    scrollspy: true,
    modal: true,
  },
};

// Generate SCSS variables string from config
export function generateScssVariables(config) {
  const lines = [];

  lines.push('// Generated by Unigrid Configurator');
  lines.push('');

  // Colors
  lines.push(`$ug-black: ${config.colors.black} !default;`);
  lines.push(`$ug-white: ${config.colors.white} !default;`);
  lines.push(`$ug-warm-gray: ${config.colors.warmGray} !default;`);
  lines.push(`$ug-dark-gray: ${config.colors.darkGray} !default;`);
  lines.push(`$ug-medium-gray: ${config.colors.mediumGray} !default;`);
  lines.push(`$ug-light-gray: ${config.colors.lightGray} !default;`);
  lines.push(`$ug-red: ${config.colors.red} !default;`);
  lines.push(`$ug-brown: ${config.colors.brown} !default;`);
  lines.push(`$ug-green: ${config.colors.green} !default;`);
  lines.push(`$ug-blue: ${config.colors.blue} !default;`);
  lines.push('');

  // Typography
  lines.push(`$ug-font-family: ${config.fontFamily} !default;`);
  lines.push(`$ug-font-family-variable: ${config.fontFamilyVariable} !default;`);
  lines.push(`$ug-base-font-size: ${config.baseFontSize}% !default;`);
  lines.push(`$ug-base-font-size-desktop: ${config.baseFontSizeDesktop}% !default;`);
  lines.push(`$ug-base-leading: ${config.baseLeading} !default;`);
  lines.push(`$ug-base-leading-desktop: ${config.baseLeadingDesktop} !default;`);
  lines.push('');

  // Border Radius
  const radius = config.borderRadius === 0 ? '0' : `${config.borderRadius}rem`;
  lines.push(`$ug-border-radius: ${radius} !default;`);
  lines.push('');

  return lines.join('\n');
}

// Generate SCSS import string based on selected components
export function generateScssImports(config) {
  const lines = [];
  lines.push('@import "variables";');
  lines.push('@import "mixins";');

  const componentMap = {
    reset: 'reset',
    container: 'container',
    grid: 'grid',
    formats: 'formats',
    broadside: 'broadside',
    header: 'header',
    navbar: 'navbar',
    footer: 'footer',
    hero: 'hero',
    section: 'section',
    typography: 'typography',
    prose: 'prose',
    buttons: 'buttons',
    dropdown: 'dropdown',
    tabs: 'tabs',
    accordion: 'accordion',
    table: 'table',
    list: 'list',
    card: 'card',
    sidebar: 'sidebar',
    forms: 'forms',
    modal: 'modal',
    pagination: 'pagination',
    scrollspy: 'scrollspy',
    modules: 'modules',
    utilities: 'utilities',
  };

  for (const [key, file] of Object.entries(componentMap)) {
    if (config.components[key]) {
      lines.push(`@import "${file}";`);
    }
  }

  return lines.join('\n');
}

// Generate CSS custom properties for live preview
export function generateCssPreview(config) {
  return `:root {
  --ug-preview-black: ${config.colors.black};
  --ug-preview-white: ${config.colors.white};
  --ug-preview-warm-gray: ${config.colors.warmGray};
  --ug-preview-red: ${config.colors.red};
  --ug-preview-brown: ${config.colors.brown};
  --ug-preview-green: ${config.colors.green};
  --ug-preview-blue: ${config.colors.blue};
  --ug-preview-radius: ${config.borderRadius === 0 ? '0' : config.borderRadius + 'rem'};
  --ug-preview-font: ${config.fontFamily};
}`;
}
